<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlStatements [
<!ELEMENT sqlStatements (sql+)>
<!ELEMENT sql (#PCDATA)>
<!ATTLIST sqlStatements namespace CDATA #REQUIRED>
<!ATTLIST sql id CDATA #REQUIRED>
]>
<!-- 
   作者：杨智能
   创建时间 ：2019-1-15
   修改时间：
 -->
<sqlStatements namespace="userQQInfo">
	<!-- SQL语句 -->
	<sql id="selectAll">
	select * from user_qq_info
	</sql>

	<sql id="selectById">
	select * from user_qq_info where user_qq_id= ?	
	</sql>

	<sql id="insert">
	insert into user_qq_info values(?,?,?,?,?)	
	</sql>

	<sql id="update">
	update user_qq_info set user_qq_name = ?, user_qq_icon = ?, user_id = ?, user_QQ_remark = ? where user_qq_id = ?			
	</sql>

	<sql id="delete">
	delete from user_qq_info where user_qq_id= ?	
	</sql>

</sqlStatements>