<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlStatements [
<!ELEMENT sqlStatements (sql+)>
<!ELEMENT sql (#PCDATA)>
<!ATTLIST sqlStatements namespace CDATA #REQUIRED>
<!ATTLIST sql id CDATA #REQUIRED>
]>
<!-- 
   作者：杨智能
   创建时间 ：2019-1-15
   修改时间：
 -->
<sqlStatements namespace="videoBrowseRecord">
	<!-- SQL语句 -->
	<sql id="selectAll">
	select * from video_browse_record
	</sql>

	<sql id="selectById">
	select * from video_browse_record where videobrowse_record_id= ?	
	</sql>

	<sql id="insert">
	insert into video_browse_record values(VIDEOBROWSERECORDID.nextval,?,?,?,?,?)	
	</sql>

	<sql id="update">
	 update video_browse_record set video_id = ?, user_id = ?, support_state = ?, browse_time = ?, remark = ? where videobrowse_record_id = ?	
	</sql>

	<sql id="delete">
		delete from video_browse_record where videobrowse_record_id= ?
	</sql>

</sqlStatements>